# Generated by Django 4.2.14 on 2024-07-10 18:43

from django.db import migrations, models
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='posted_timestamp',
            field=models.DateTimeField(default=meetings.models.default_posted_timestamp),
        ),
        migrations.AddField(
            model_name='device',
            name='device_catalog',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='device_description',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='posted_timestamp',
            field=models.DateTimeField(default=meetings.models.default_posted_timestamp),
        ),
        migrations.AddField(
            model_name='doctor',
            name='posted_timestamp',
            field=models.DateTimeField(default=meetings.models.default_posted_timestamp),
        ),
        migrations.AddField(
            model_name='meeting',
            name='instrument_specifications',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='posted_timestamp',
            field=models.DateTimeField(default=meetings.models.default_posted_timestamp),
        ),
    ]
