# Generated by Django 4.2.14 on 2024-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_device_faq_remove_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='posted_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='posted_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='posted_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='posted_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
