# Generated by Django 4.2.14 on 2024-07-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='meeting',
        ),
    ]
